cstock_articles:
    resource: "@cstockArticlesBundle/Controller/"
    type:     annotation
    prefix:   /

cstock_main:
    resource: "@cstockMainBundle/Controller/"
    type:     annotation
    prefix:   /

